// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw-SRCZSLabWfgqnz_kCWgHv2kF4csgWo',
    appId: '1:126461812400:android:36ad7c268996f0d99d6575',
    messagingSenderId: '126461812400',
    projectId: 'notify-fd0e9',
    storageBucket: 'notify-fd0e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFFgy4taw2KK-pTRRl1aC1za1nJ0h-zic',
    appId: '1:126461812400:ios:7c020e4612910cc59d6575',
    messagingSenderId: '126461812400',
    projectId: 'notify-fd0e9',
    storageBucket: 'notify-fd0e9.firebasestorage.app',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOZAd5wBszuMqcHROjhZM4Vi_gphtUyHs',
    appId: '1:126461812400:web:ade41879daa046d59d6575',
    messagingSenderId: '126461812400',
    projectId: 'notify-fd0e9',
    authDomain: 'notify-fd0e9.firebaseapp.com',
    storageBucket: 'notify-fd0e9.firebasestorage.app',
    measurementId: 'G-52GT67KQYJ',
  );

}